### ISSUE TITLE
server download using curl flow is not working

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic-community/RunDMC#772] opened 2018-02-05 20:39 UTC
From the ML9 download page (https://developer.marklogic.com/products), if you click on the link for the RHEL7 download (MarkLogic Server x64 (AMD64, Intel EM64T) 64-bit Linux RPM), you get a dialog which requires you to accept the license agreement and then click on either "Download" or "Download Via curl".

If you click on "Download Via curl", you get a "MarkLogic Download URL" dialog box that is sadly devoid of URLs:

![curl_download](https://user-images.githubusercontent.com/1951367/35827562-55cf3b30-0a71-11e8-91a0-5e201cf72bbe.gif)

If you try the same thing from the ML8 download page (https://developer.marklogic.com/products/marklogic-server/8.0), absolutely nothing happens when you click the "Download Via curl" button. No dialog, nada.

A secondary, very minor problem with the "MarkLogic Download URL" dialog is that the close button in the upper right corner looks like a radio button because the X one might normally expect to see there is absent. (Or more likely, the same color as the enclosing box.)

**Comment by kcoleman-marklogic** [comment] 2018-02-05 20:46
I take back part of what I said: ML8 behaves the same as ML9 (dialog box with no URLs), though it is possible to make it do nothing. The do-nothing case feels like a caching problem. To wit:

If you check the agreement box and then dismiss the dialog box, the next time you click on the download link to bring up that dialog, the agreement box is still checked. In this case, clicking on download does nothing. You have to uncheck and re-check the agreement box to get things moving. At least, using Chrome.

**Comment by dmcassel** [comment] 2018-02-06 16:50
The problem is an old version of jquery-ui and much newer version of jquery, inherited from the mega-nav. Working on a fix.

**Comment by dmcassel** [comment] 2018-02-06 18:53
@kcoleman-marklogic I just pushed a fix to production. I'll close this, but reopen it and let me know if you see any trouble.

**Closed by dmcassel** 2018-02-06 18:53 UTC
Labels: bug, dmc app
